//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class broker_employees
    {
        public int ID { get; set; }
        public string BrokerID { get; set; }
        public string EmployeID { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual aspnetuser aspnetuser1 { get; set; }
    }
}
