//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat_requests
    {
        public int ID { get; set; }
        public string Requested_by { get; set; }
        public System.DateTime Datetime_request { get; set; }
        public string Accepted_by { get; set; }
        public bool Accepted { get; set; }
    }
}
