//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;

    public partial class client
    {
        public int id { get; set; }
        public string FirstLastName { get; set; }
        public string StreetNumber { get; set; }
        public string City { get; set; }
        public Nullable<int> PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public string MailAdress { get; set; }
        public string PassportNumber { get; set; }
        public string EMBG { get; set; }
    }
}
