//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class config_policy_values
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public int IDPolicy { get; set; }
    
        public virtual config_policy config_policy { get; set; }
    }
}
