//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_users
    {
        public int ID { get; set; }
        public int EventID { get; set; }
        public string UserID { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual @event @event { get; set; }
    }
}
