//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class insured
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public insured()
        {
            this.bank_account_info = new HashSet<bank_account_info>();
            this.first_notice_of_loss = new HashSet<first_notice_of_loss>();
            this.first_notice_of_loss_archive = new HashSet<first_notice_of_loss_archive>();
            this.policy_insured = new HashSet<policy_insured>();
            this.travel_policy = new HashSet<travel_policy>();
            this.insured_log = new HashSet<insured_log>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public string SSN { get; set; }
        public System.DateTime DateBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public string City { get; set; }
        public string Postal_Code { get; set; }
        public string Address { get; set; }
        public string Passport_Number_IdNumber { get; set; }
        public Nullable<int> Type_InsuredID { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public string Modified_By { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bank_account_info> bank_account_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<first_notice_of_loss> first_notice_of_loss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<first_notice_of_loss_archive> first_notice_of_loss_archive { get; set; }
        public virtual type_insured type_insured { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<policy_insured> policy_insured { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<travel_policy> travel_policy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insured_log> insured_log { get; set; }
    }
}
