//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_activities
    {
        public long Log_Activity_ID { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string IP_Address { get; set; }
        public System.DateTime Time_Stamp { get; set; }
    }
}
