//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class luggage_insurance_info
    {
        public int Additional_infoId { get; set; }
        public string Place_description { get; set; }
        public string Detail_description { get; set; }
        public string Report_place { get; set; }
        public string Floaters { get; set; }
        public Nullable<float> Floaters_value { get; set; }
        public System.TimeSpan Luggage_checking_Time { get; set; }
    
        public virtual additional_info additional_info { get; set; }
    }
}
