//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authentication.WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class news_all
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string ImageLocation { get; set; }
        public string Content { get; set; }
        public bool IsNotification { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string InsurenceCompany { get; set; }
        public string GroupID { get; set; }
        public string UserID { get; set; }
    }
}
