//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificationuser
    {
        public int Id { get; set; }
        public int NotificationId { get; set; }
        public string UserId { get; set; }
        public bool IsOpened { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual notification notification { get; set; }
    }
}
