//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ok_setup
    {
        public int id { get; set; }
        public int Sms_Code_Seconds { get; set; }
        public int NumberOfAttempts { get; set; }
        public int NumberOfNews { get; set; }
        public System.TimeSpan NotificationTime { get; set; }
        public int NumberOfLastMsg { get; set; }
        public string InsuranceCompany { get; set; }
        public int VersionNumber { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public string Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public sbyte SSNValidationActive { get; set; }
        public Nullable<sbyte> TestPayment { get; set; }
    }
}
