//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;

    public partial class p_familija
    {
        public long I_Familija { get; set; }
        public string Vid_Polisa { get; set; }
        public Nullable<double> Popust_Familija { get; set; }
    }
}
