//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;

    public partial class p_fran
    {
        public string Fransiza { get; set; }
        public string Dedactible { get; set; }
        public Nullable<int> I_Fran { get; set; }
    }
}
