//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;

    public partial class p_grupa
    {
        public long I_Grupa { get; set; }
        public string Vid_Polisa { get; set; }
        public Nullable<long> Grupa { get; set; }
        public Nullable<double> Popust_Grupa { get; set; }
    }
}
