//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_min_premija
    {
        public long I_Min { get; set; }
        public string Vid_Polisa { get; set; }
        public Nullable<double> Minimalna_Premija { get; set; }
    }
}
