//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authentication.WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_referent
    {
        public string Sifra { get; set; }
        public string Referent { get; set; }
        public string Ovlastena_Agencija { get; set; }
        public string Sifra_Deloven_Partner { get; set; }
    }
}
