//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_vozrast
    {
        public int ID { get; set; }
        public Nullable<double> Vozrast { get; set; }
        public Nullable<double> P_Vozrast1 { get; set; }
    }
}
