//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;

    public partial class p_zemja_na_patuvanje
    {
        public long I_Zemja_Na_Patuvanje { get; set; }
        public string Zemja_Na_Patuvanje { get; set; }
        public string Vid_Polisa { get; set; }
        public Nullable<double> Procent_Zemja_Na_Patuvanje { get; set; }
        public string Fransiza { get; set; }
        public Nullable<double> Popust_Fransiza { get; set; }
    }
}
