//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class patnicko
    {
        public long Polisa_Broj { get; set; }
        public Nullable<double> Kurs { get; set; }
        public string Zemja_Na_Patuvanje { get; set; }
        public Nullable<double> Procent_Zemja_Na_Patuvanje { get; set; }
        public string Vid_Polisa { get; set; }
        public string Fransiza { get; set; }
        public string Dedactible { get; set; }
        public Nullable<double> Popust_Fransiza { get; set; }
        public string Ime_I_Prezime { get; set; }
        public string Adresa { get; set; }
        public string EMBG { get; set; }
        public Nullable<double> P_Vozrast { get; set; }
        public string Fransiza_Vozrast { get; set; }
        public string Dedactible_Age { get; set; }
        public string Broj_Pasos { get; set; }
        public Nullable<System.DateTime> Zapocnuva_Na { get; set; }
        public Nullable<System.DateTime> Zavrsuva_Na { get; set; }
        public Nullable<long> Vazi_Denovi { get; set; }
        public Nullable<double> Popust_Denovi { get; set; }
        public string Fransiza_Denovi { get; set; }
        public string Dedactible_Period { get; set; }
        public Nullable<bool> Pat_Edno { get; set; }
        public Nullable<bool> Pat_Poveke { get; set; }
        public Nullable<bool> Vid_Poedinecno { get; set; }
        public Nullable<bool> Vid_Grupno { get; set; }
        public Nullable<bool> Vid_Familijarno { get; set; }
        public Nullable<bool> Vid_Biznis { get; set; }
        public Nullable<double> Popust_Business { get; set; }
        public Nullable<double> Popust_Familija { get; set; }
        public string Osigurenik1_Ime_I_Prezime { get; set; }
        public string Osigurenik1_EMBG { get; set; }
        public Nullable<double> P_Vozrast1 { get; set; }
        public string Osigurenik2_Ime_I_Prezime { get; set; }
        public string Osigurenik2_EMBG { get; set; }
        public Nullable<double> P_Vozrast2 { get; set; }
        public string Osigurenik3_Ime_I_Prezime { get; set; }
        public string Osigurenik3_EMBG { get; set; }
        public Nullable<double> P_Vozrast3 { get; set; }
        public string Osigurenik4_Ime_I_Prezime { get; set; }
        public string Osigurenik4_EMBG { get; set; }
        public Nullable<double> P_Vozrast4 { get; set; }
        public string Osigurenik5_Ime_I_Prezime { get; set; }
        public string Osigurenik5_EMBG { get; set; }
        public Nullable<double> P_Vozrast5 { get; set; }
        public string Osigurenik6_Ime_I_Prezime { get; set; }
        public string Osigurenik6_EMBG { get; set; }
        public Nullable<double> P_Vozrast6 { get; set; }
        public Nullable<int> Grupa { get; set; }
        public Nullable<double> Popust_Grupa { get; set; }
        public Nullable<double> Grupna_Vkupna_Premija { get; set; }
        public Nullable<double> Osnovna_Premija { get; set; }
        public string Doplatok_1 { get; set; }
        public Nullable<double> P_Doplatok_1 { get; set; }
        public string Doplatok_2 { get; set; }
        public Nullable<double> P_Doplatok_2 { get; set; }
        public Nullable<double> Vkupna_Premija { get; set; }
        public string Ovlastena_Agencija { get; set; }
        public string Sifra { get; set; }
        public string Referent { get; set; }
        public Nullable<System.DateTime> Datum_Na_Izdavanje { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Datum_Na_Storniranje { get; set; }
        public string BRoj_Polisa_Kompanija { get; set; }
    }
}
