//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class points_requests
    {
        public int id { get; set; }
        public string id_user { get; set; }
        public string ssn { get; set; }
        public string policy_id { get; set; }
        public System.DateTime timestamp { get; set; }
        public Nullable<bool> flag { get; set; }
    }
}
