//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class policy_insured
    {
        public int ID { get; set; }
        public int PolicyID { get; set; }
        public int InsuredID { get; set; }
    
        public virtual insured insured { get; set; }
        public virtual travel_policy travel_policy { get; set; }
    }
}
