//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InsuredTraveling.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin site.
        /// </summary>
        public static string Home_AdminPanel {
            get {
                return ResourceManager.GetString("Home_AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Notice of Loss.
        /// </summary>
        public static string Home_FirstNoticeOfLoss {
            get {
                return ResourceManager.GetString("Home_FirstNoticeOfLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Client.
        /// </summary>
        public static string Home_NewClient {
            get {
                return ResourceManager.GetString("Home_NewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Policy.
        /// </summary>
        public static string Home_NewPolicy {
            get {
                return ResourceManager.GetString("Home_NewPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string Home_News {
            get {
                return ResourceManager.GetString("Home_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Home_Search {
            get {
                return ResourceManager.GetString("Home_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Offers.
        /// </summary>
        public static string Policy_AddOffer {
            get {
                return ResourceManager.GetString("Policy_AddOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-on.
        /// </summary>
        public static string Policy_AddOn {
            get {
                return ResourceManager.GetString("Policy_AddOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Policy.
        /// </summary>
        public static string Policy_BuyPolicy {
            get {
                return ResourceManager.GetString("Policy_BuyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Premium.
        /// </summary>
        public static string Policy_CalculatePremium {
            get {
                return ResourceManager.GetString("Policy_CalculatePremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Policy.
        /// </summary>
        public static string Policy_CreatePolicy {
            get {
                return ResourceManager.GetString("Policy_CreatePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Policy_Days {
            get {
                return ResourceManager.GetString("Policy_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductible.
        /// </summary>
        public static string Policy_Deductible {
            get {
                return ResourceManager.GetString("Policy_Deductible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductible By Age.
        /// </summary>
        public static string Policy_DeductibleByAge {
            get {
                return ResourceManager.GetString("Policy_DeductibleByAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductible By Day.
        /// </summary>
        public static string Policy_DeductibleByDay {
            get {
                return ResourceManager.GetString("Policy_DeductibleByDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Policy_Duration {
            get {
                return ResourceManager.GetString("Policy_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing User.
        /// </summary>
        public static string Policy_ExistingUser {
            get {
                return ResourceManager.GetString("Policy_ExistingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter data for all the fields!.
        /// </summary>
        public static string Policy_FillData {
            get {
                return ResourceManager.GetString("Policy_FillData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Policy_HolderAddress {
            get {
                return ResourceManager.GetString("Policy_HolderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string Policy_HolderBirthDay {
            get {
                return ResourceManager.GetString("Policy_HolderBirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Policy_HolderCity {
            get {
                return ResourceManager.GetString("Policy_HolderCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Policy_HolderEmail {
            get {
                return ResourceManager.GetString("Policy_HolderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder Information.
        /// </summary>
        public static string Policy_HolderInformation {
            get {
                return ResourceManager.GetString("Policy_HolderInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Policy_HolderLastName {
            get {
                return ResourceManager.GetString("Policy_HolderLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Policy_HolderName {
            get {
                return ResourceManager.GetString("Policy_HolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport/ID Cart Number.
        /// </summary>
        public static string Policy_HolderPassport {
            get {
                return ResourceManager.GetString("Policy_HolderPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Policy_HolderPhone {
            get {
                return ResourceManager.GetString("Policy_HolderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Policy_HolderPostalCode {
            get {
                return ResourceManager.GetString("Policy_HolderPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder is insured.
        /// </summary>
        public static string Policy_HolderSameInsured {
            get {
                return ResourceManager.GetString("Policy_HolderSameInsured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN.
        /// </summary>
        public static string Policy_HolderSSN {
            get {
                return ResourceManager.GetString("Policy_HolderSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am insured.
        /// </summary>
        public static string Policy_IamInsured {
            get {
                return ResourceManager.GetString("Policy_IamInsured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Policy_InsuredAddress {
            get {
                return ResourceManager.GetString("Policy_InsuredAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string Policy_InsuredBirthDate {
            get {
                return ResourceManager.GetString("Policy_InsuredBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Policy_InsuredCity {
            get {
                return ResourceManager.GetString("Policy_InsuredCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Policy_InsuredEmail {
            get {
                return ResourceManager.GetString("Policy_InsuredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured Information.
        /// </summary>
        public static string Policy_InsuredInformation {
            get {
                return ResourceManager.GetString("Policy_InsuredInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Policy_InsuredLastName {
            get {
                return ResourceManager.GetString("Policy_InsuredLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Policy_InsuredName {
            get {
                return ResourceManager.GetString("Policy_InsuredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport/ ID Cart Number.
        /// </summary>
        public static string Policy_InsuredPassport {
            get {
                return ResourceManager.GetString("Policy_InsuredPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Policy_InsuredPhone {
            get {
                return ResourceManager.GetString("Policy_InsuredPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Policy_InsuredPostalCode {
            get {
                return ResourceManager.GetString("Policy_InsuredPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN.
        /// </summary>
        public static string Policy_InsuredSSN {
            get {
                return ResourceManager.GetString("Policy_InsuredSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Trips.
        /// </summary>
        public static string Policy_MoreTrip {
            get {
                return ResourceManager.GetString("Policy_MoreTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Members.
        /// </summary>
        public static string Policy_NumberMembers {
            get {
                return ResourceManager.GetString("Policy_NumberMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Trips.
        /// </summary>
        public static string Policy_NumberTrips {
            get {
                return ResourceManager.GetString("Policy_NumberTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Trip.
        /// </summary>
        public static string Policy_OneTrip {
            get {
                return ResourceManager.GetString("Policy_OneTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Data.
        /// </summary>
        public static string Policy_PolicyData {
            get {
                return ResourceManager.GetString("Policy_PolicyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Effective Date.
        /// </summary>
        public static string Policy_PolicyEffectiveDate {
            get {
                return ResourceManager.GetString("Policy_PolicyEffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Expiry Date.
        /// </summary>
        public static string Policy_PolicyExpiryDate {
            get {
                return ResourceManager.GetString("Policy_PolicyExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Policy_PolicyFamily {
            get {
                return ResourceManager.GetString("Policy_PolicyFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Policy_PolicyGroup {
            get {
                return ResourceManager.GetString("Policy_PolicyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Information.
        /// </summary>
        public static string Policy_PolicyInformation {
            get {
                return ResourceManager.GetString("Policy_PolicyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Policy_PolicySingle {
            get {
                return ResourceManager.GetString("Policy_PolicySingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Type.
        /// </summary>
        public static string Policy_PolicyType {
            get {
                return ResourceManager.GetString("Policy_PolicyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print offers.
        /// </summary>
        public static string Policy_PrintOffer {
            get {
                return ResourceManager.GetString("Policy_PrintOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Premium.
        /// </summary>
        public static string Policy_TotalPremium {
            get {
                return ResourceManager.GetString("Policy_TotalPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Premium in Group.
        /// </summary>
        public static string Policy_TotalPremiumInGroup {
            get {
                return ResourceManager.GetString("Policy_TotalPremiumInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Country.
        /// </summary>
        public static string Policy_TravelCountry {
            get {
                return ResourceManager.GetString("Policy_TravelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Type.
        /// </summary>
        public static string Policy_Type {
            get {
                return ResourceManager.GetString("Policy_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have at least one valid day!.
        /// </summary>
        public static string Policy_ValidDate {
            get {
                return ResourceManager.GetString("Policy_ValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation date.
        /// </summary>
        public static string Seacrh_SearchTableCancellationDate {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableCancellationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Seacrh_SearchTableCity {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimant Name and Last Name.
        /// </summary>
        public static string Seacrh_SearchTableClaimantNameLastName {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableClaimantNameLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Seacrh_SearchTableEmail {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy effective date.
        /// </summary>
        public static string Seacrh_SearchTableFrom {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Insurance Yes/No.
        /// </summary>
        public static string Seacrh_SearchTableHealthInsurance {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableHealthInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship between the policyholder and the insured.
        /// </summary>
        public static string Seacrh_SearchTableInsuredHolderRelationship {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableInsuredHolderRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured Name and Last Name.
        /// </summary>
        public static string Seacrh_SearchTableInsuredNameLastName {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableInsuredNameLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Seacrh_SearchTableLastName {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luggage Insurance Yes/No.
        /// </summary>
        public static string Seacrh_SearchTableLuggageInsurance {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableLuggageInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Seacrh_SearchTableName {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        public static string Seacrh_SearchTablePassport {
            get {
                return ResourceManager.GetString("Seacrh_SearchTablePassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Seacrh_SearchTablePhoneNumber {
            get {
                return ResourceManager.GetString("Seacrh_SearchTablePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy issuance date.
        /// </summary>
        public static string Seacrh_SearchTablePolicyIssuanceDate {
            get {
                return ResourceManager.GetString("Seacrh_SearchTablePolicyIssuanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Type.
        /// </summary>
        public static string Seacrh_SearchTablePolicyType {
            get {
                return ResourceManager.GetString("Seacrh_SearchTablePolicyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Seacrh_SearchTablePostalCode {
            get {
                return ResourceManager.GetString("Seacrh_SearchTablePostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of FNOL.
        /// </summary>
        public static string Seacrh_SearchTableRegistrationDate {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN.
        /// </summary>
        public static string Seacrh_SearchTableSSN {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Seacrh_SearchTableStreet {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy expiry date.
        /// </summary>
        public static string Seacrh_SearchTableTo {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string Seacrh_SearchTableTotalCost {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableTotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Country.
        /// </summary>
        public static string Seacrh_SearchTableTravelCountry {
            get {
                return ResourceManager.GetString("Seacrh_SearchTableTravelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New FNOL.
        /// </summary>
        public static string Search_AddFNOL {
            get {
                return ResourceManager.GetString("Search_AddFNOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New FNOL.
        /// </summary>
        public static string Search_AddFNOLLink {
            get {
                return ResourceManager.GetString("Search_AddFNOLLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new client.
        /// </summary>
        public static string Search_AddNewClient {
            get {
                return ResourceManager.GetString("Search_AddNewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Policy.
        /// </summary>
        public static string Search_AddPolicyButton {
            get {
                return ResourceManager.GetString("Search_AddPolicyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation Date.
        /// </summary>
        public static string Search_CancellationDate {
            get {
                return ResourceManager.GetString("Search_CancellationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimant Last Name.
        /// </summary>
        public static string Search_ClaimantLastName {
            get {
                return ResourceManager.GetString("Search_ClaimantLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimant Name.
        /// </summary>
        public static string Search_ClaimantName {
            get {
                return ResourceManager.GetString("Search_ClaimantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Search_Clients {
            get {
                return ResourceManager.GetString("Search_Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Search_DetailsLink {
            get {
                return ResourceManager.GetString("Search_DetailsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Notice of Loss.
        /// </summary>
        public static string Search_FNOL {
            get {
                return ResourceManager.GetString("Search_FNOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FNOL.
        /// </summary>
        public static string Search_FNOLLink {
            get {
                return ResourceManager.GetString("Search_FNOLLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Insurance.
        /// </summary>
        public static string Search_HealthInsurance {
            get {
                return ResourceManager.GetString("Search_HealthInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Holder Last Name.
        /// </summary>
        public static string Search_HolderLastName {
            get {
                return ResourceManager.GetString("Search_HolderLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Holder Name.
        /// </summary>
        public static string Search_HolderName {
            get {
                return ResourceManager.GetString("Search_HolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured Last Name.
        /// </summary>
        public static string Search_InsuredLastName {
            get {
                return ResourceManager.GetString("Search_InsuredLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured Name.
        /// </summary>
        public static string Search_InsuredName {
            get {
                return ResourceManager.GetString("Search_InsuredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured Policy.
        /// </summary>
        public static string Search_InsuredPolicy {
            get {
                return ResourceManager.GetString("Search_InsuredPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luggage Insurance.
        /// </summary>
        public static string Search_LuggageInsurance {
            get {
                return ResourceManager.GetString("Search_LuggageInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string Search_Policy {
            get {
                return ResourceManager.GetString("Search_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Effective Date.
        /// </summary>
        public static string Search_PolicyEffectiveDate {
            get {
                return ResourceManager.GetString("Search_PolicyEffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Expiry Date.
        /// </summary>
        public static string Search_PolicyExpiryDate {
            get {
                return ResourceManager.GetString("Search_PolicyExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Issuance Date.
        /// </summary>
        public static string Search_PolicyIssuanceDate {
            get {
                return ResourceManager.GetString("Search_PolicyIssuanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string Search_PolicyLink {
            get {
                return ResourceManager.GetString("Search_PolicyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Number.
        /// </summary>
        public static string Search_PolicyNumber {
            get {
                return ResourceManager.GetString("Search_PolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Holder.
        /// </summary>
        public static string Search_PolicyPolicyHolder {
            get {
                return ResourceManager.GetString("Search_PolicyPolicyHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Type.
        /// </summary>
        public static string Search_PolicyType {
            get {
                return ResourceManager.GetString("Search_PolicyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string Search_RegistrationDate {
            get {
                return ResourceManager.GetString("Search_RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Address.
        /// </summary>
        public static string Search_SearchAddress {
            get {
                return ResourceManager.GetString("Search_SearchAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_SearchButton {
            get {
                return ResourceManager.GetString("Search_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By City.
        /// </summary>
        public static string Search_SearchCity {
            get {
                return ResourceManager.GetString("Search_SearchCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Email.
        /// </summary>
        public static string Search_SearchEmail {
            get {
                return ResourceManager.GetString("Search_SearchEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Last Name.
        /// </summary>
        public static string Search_SearchLastName {
            get {
                return ResourceManager.GetString("Search_SearchLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Name.
        /// </summary>
        public static string Search_SearchName {
            get {
                return ResourceManager.GetString("Search_SearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Passport.
        /// </summary>
        public static string Search_SearchPassport {
            get {
                return ResourceManager.GetString("Search_SearchPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Phone Number.
        /// </summary>
        public static string Search_SearchPhoneNumber {
            get {
                return ResourceManager.GetString("Search_SearchPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by postal code.
        /// </summary>
        public static string Search_SearchPostalCode {
            get {
                return ResourceManager.GetString("Search_SearchPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by SSN.
        /// </summary>
        public static string Search_SearchSSN {
            get {
                return ResourceManager.GetString("Search_SearchSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Number.
        /// </summary>
        public static string Search_SearchTablePolicyNumber {
            get {
                return ResourceManager.GetString("Search_SearchTablePolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string Search_TotalCost {
            get {
                return ResourceManager.GetString("Search_TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Country.
        /// </summary>
        public static string Search_TravelCountry {
            get {
                return ResourceManager.GetString("Search_TravelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With no Add-on.
        /// </summary>
        public static string WithNoAddOn {
            get {
                return ResourceManager.GetString("WithNoAddOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
