//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class sava_sale_points
    {
        public int id { get; set; }
        public string location_name { get; set; }
        public string street { get; set; }
        public string municipality { get; set; }
        public string postalcode { get; set; }
        public string phone_number { get; set; }
        public string opening_hours { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public bool insurance_deal { get; set; }
        public bool insurance_report { get; set; }
        //public Nullable<bool> insurance_deal { get; set; }
        //public Nullable<bool> insurance_report { get; set; }
    }
}
