//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class sava_voucher
    {
        public int id { get; set; }
        public string voucher_code { get; set; }
        public string id_policyHolder { get; set; }
        public float points_used { get; set; }
        public string id_seller { get; set; }
        public System.DateTime timestamp { get; set; }
    }
}
