//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class sava_policy
    {
        public int id { get; set; }
        public int policy_number { get; set; }
        public string SSN_insured { get; set; }
        public string SSN_policyHolder { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public float premium { get; set; }
        public string email_seller { get; set; }
        public float discount_points { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
    }
}
