//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class sava_setup
    {
        public int id { get; set; }
        public string email_administrator { get; set; }
        public float points_percentage { get; set; }
        public float vip_sum { get; set; }
        public int version { get; set; }
        public string last_modify_by { get; set; }
        public System.DateTime timestamp { get; set; }
        public bool Active { get; set; }
    }
}
