//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authentication.WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int OrderID { get; set; }
        public string TRANID { get; set; }
        public string islemtipi { get; set; }
        public string merchantID { get; set; }
        public string amount { get; set; }
        public string sID { get; set; }
        public string ACQBIN { get; set; }
        public string xid { get; set; }
        public string mdStatus { get; set; }
        public string ProcReturnCode { get; set; }
        public string Response { get; set; }
        public string mdErrorMsg { get; set; }
        public string ErrMsg { get; set; }
        public string HASH { get; set; }
        public string Ime_i_Prezime { get; set; }
    }
}
