//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuredTraveling
{
    using System;
    using System.Collections.Generic;
    
    public partial class travel_policy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public travel_policy()
        {
            this.first_notice_of_loss = new HashSet<first_notice_of_loss>();
            this.policy_additional_charge = new HashSet<policy_additional_charge>();
            this.policy_insured = new HashSet<policy_insured>();
            this.first_notice_of_loss_archive = new HashSet<first_notice_of_loss_archive>();
        }
    
        public int ID { get; set; }
        public string Policy_Number { get; set; }
        public int Policy_HolderID { get; set; }
        public int Exchange_RateID { get; set; }
        public int CountryID { get; set; }
        public int Policy_TypeID { get; set; }
        public int Retaining_RiskID { get; set; }
        public string Franchise_Age { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public int Valid_Days { get; set; }
        public string Franchise_Days { get; set; }
        public int Travel_NumberID { get; set; }
        public int Travel_Insurance_TypeID { get; set; }
        public Nullable<int> Group_Members { get; set; }
        public Nullable<double> Group_Total_Premium { get; set; }
        public Nullable<double> Total_Premium { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Cancellation { get; set; }
        public bool Payment_Status { get; set; }


      

        public Nullable<System.DateTime> Date_Cancellation { get; set; }

        public Nullable<int> Discount { get; set; }

    
        public virtual country country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<first_notice_of_loss> first_notice_of_loss { get; set; }
        public virtual insured insured { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<policy_additional_charge> policy_additional_charge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<policy_insured> policy_insured { get; set; }
        public virtual policy_type policy_type { get; set; }
        public virtual retaining_risk retaining_risk { get; set; }
        public virtual travel_insurance_type travel_insurance_type { get; set; }
        public virtual travel_number travel_number { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<first_notice_of_loss_archive> first_notice_of_loss_archive { get; set; }
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual aspnetuser aspnetuser1 { get; set; }
    }
}
