
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InsuredTraveling
{

using System;
    using System.Collections.Generic;
    
public partial class user
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public user()
    {

        this.kanbantickets = new HashSet<kanbanticket>();

        this.kanbantickets1 = new HashSet<kanbanticket>();

    }


    public int ID { get; set; }

    public string FisrtName { get; set; }

    public string LastName { get; set; }

    public string SSN { get; set; }

    public string PhoneNumber { get; set; }

    public string PostalCode { get; set; }

    public string Address { get; set; }

    public string Municipality { get; set; }

    public string City { get; set; }

    public string AspNetUserID { get; set; }

    public string PassportNumber_UID { get; set; }

    public System.DateTime DateBirth { get; set; }

    public string Gender { get; set; }



    public virtual aspnetuser aspnetuser { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<kanbanticket> kanbantickets { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<kanbanticket> kanbantickets1 { get; set; }

}

}
