//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authentication.WEB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class InsuredTravelingEntity : DbContext
    {
        public InsuredTravelingEntity()
            : base("name=InsuredTravelingEntity")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<client> client { get; set; }
        public DbSet<eurolinkusers> eurolinkusers { get; set; }
        public DbSet<news_all> news_all { get; set; }
        public DbSet<p_den> p_den { get; set; }
        public DbSet<p_denovi> p_denovi { get; set; }
        public DbSet<p_doplatoci> p_doplatoci { get; set; }
        public DbSet<p_familija> p_familija { get; set; }
        public DbSet<p_fran> p_fran { get; set; }
        public DbSet<p_grupa> p_grupa { get; set; }
        public DbSet<p_kurs> p_kurs { get; set; }
        public DbSet<p_min_premija> p_min_premija { get; set; }
        public DbSet<p_referent> p_referent { get; set; }
        public DbSet<p_stapki> p_stapki { get; set; }
        public DbSet<p_vozrast> p_vozrast { get; set; }
        public DbSet<p_zem> p_zem { get; set; }
        public DbSet<p_zemja_na_patuvanje> p_zemja_na_patuvanje { get; set; }
        public DbSet<patnicko> patnicko { get; set; }
        public DbSet<patnicko_vid> patnicko_vid { get; set; }
        public DbSet<transaction> transaction { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<user_all> user_all { get; set; }
    }
}
